name: Build Rust Binaries

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-macos-arm64:
    uses: bbusse/github-workflows/.github/workflows/build-rust.yml@dev
    with:
      binary_name: vju
      artifact_name: vju
      musl: true

  build-apk:
    uses: bbusse/github-workflows/.github/workflows/build-apk.yml@dev
    with:
      artifact_name: vju
      build_from_source: true
    secrets: inherit

  build-gentoo-pkg:
    uses: bbusse/github-workflows/.github/workflows/build-gentoo-pkg.yml@dev
    with:
      overlay_repo: bbusse/bbusse-overlay
      ebuild_path: x11-misc/vju/vju-0.1.0.ebuild
      disable: true
